// **** FULL REDUX INTEGRATION NOT CURRENTLY IMPLEMENTED ***
// **** THIS CODE IS A STARTING POINT ****
export const SET_CURRENT_PHONE_NUMBER = 'SET_CURRENT_PHONE_NUMBER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
