export const SET_CLIENT_KEY = 'SET_CLIENT_KEY';
export const INITIAL_CLIENT_PROFILE_FIELDS = 'INITIAL_PROFILE_FIELDS';
export const UPDATE_CLIENT_PROFILE = 'UPDATE_PROFLE';
export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_POSTS_BY_PROFILE = 'GET_POSTS_BY_PROFILE';
export const CLEAR_PROFILE_SCREEN = 'CLEAR_PROFILE_SCREEN';
export const SET_PROFILE_ON_PROFILESCREEN = 'SET_PROFILE_ON_PROFILESCREEN';
export const SET_PROFILE_KEY = 'SET_PROFILE_KEY';
