export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_USERS = "GET_USERS";

// For sockets
export const CONNECT_SOCKET = "CONNECT_SOCKET"
export const GOT_MESSAGES = 'GOT_MESSAGES';
export const GOT_NEW_MESSAGE = 'GOT_NEW_MESSAGE';
export const GOT_USERS = 'GOT_USERS';
export const GOT_NEW_USER = 'GOT_NEW_USER';